### ISSUE TITLE
SetSettings does not appear to set settings properly

### ISSUE THREAD

**Issue by csharpfritz** [FritzAndFriends/StreamDeckToolkit#4]
We are unable to fetch settings properly after they've been set

**Comment by NotMyself** [comment]
Can you add a little context?

**Comment by csharpfritz** [comment]
Calling 'SetSettings' against the StreamDeck API does not appear to save the settings payload and retrieve it properly from the Stream Deck application.

Check the MySamplePlugin/OnWillAppear method for fetching settings, and the OnWillDisappear method for saving the settings.  These methods fire when the button is shown in a folder or when you navigate to a different folder on the device

**Comment by codingbandit** [comment]
Per the release notes of the beta version of the StreamDeck API - this is a known issue and will be fixed in the next version (along with the introduction of getSettings) - there will also be setGlobalSettings, and getGlobalSettings

**Comment by hugodahl** [comment]
Recommend closing this issue since this has been corrected in the latest version (v4.1) of the software and the SDK (v2).

**Comment by GameDevRaccoon** [comment]
Still not triggering for me in the latest version (v4.1.0.9958), SDK (v2) and StreamDeckLib(0.4.480)
